---
# !!! KEEP THE ORDER OF THE CONFIGURATION !!!

defaults:
  # default event length in minutes when only start is specified
  default_event_length: 60
  no_date_action: 'skip' # ['skip', 'today']

time:
  timezone_name: 'Europe/Berlin'
  timezone_diff: '+02:00'

notion:
  # Page url with ?v and &p= 
  database_url: 'https://www.notion.so/*/***?v=***&p='
  token: '***'
  columns:
    name: 'Name'
    date: 'Date'
    tags: 'Tags'
    description: 'Description'
    location: 'Location'
    last_updated_time: 'Last Updated'
    last_synced_time: 'Last Synced'
    gcal_event_id: 'GCal event Id'
    recurrent_event: 'GCal Recurrence'
    gcal_event_url: 'GCal event url'
    gcal_calendar_name: 'Calendar'
    gcal_calendar_id: 'GCal calendar Id'
    to_delete: 'Delete?'
    deleted: 'Deleted'
    read_only: 'Read Only'

gcal:
  default_calendar_id: '***@gmail.com'
  default_calendar_name: General
  calendars:
    General: '***@gmail.com' # Should match default_calendar_name and default_calendar_id
    Work: '***@group.calendar.google.com'
